spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/{bd}
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQDialect
    show-sql: true
    properties:
      hibernate:
        format_sal: true
